### ISSUE TITLE
Question on details with code and paper

### ISSUE THREAD

**Issue by Kin-Zhang** [itailang/SCOOP#6]
Thanks for your work. and open source. I have some questions when I read the paper and review the code. Looking forward to your reply.

1. It seems the code and paper `Matching Cost` said C is limited by a distance of 10m, out of 10 is infinity. But the code shows no change, if we return `S`
Here is the code part:
https://github.com/itailang/SCOOP/blob/9f41e8baafed8689be867b8ab7b10159371de37d/tools/ot.py#L33-L49

![image](https://github.com/itailang/SCOOP/assets/35365764/8ebb73a9-1d6a-4cd8-a248-c14487f218c0)

2. code part on https://github.com/itailang/SCOOP/tree/master/scripts shows the max num of pts is 8192, when I tried to raw points with high channel LiDAR, the memory is not possible to allocate, especially when we use the distance matrix `BxNxM`. Did you try with around 107,000 pts?

**Comment by itailang** [comment]
Dear @Kin-Zhang,

Thank you for your interest in the paper and code.

Let me answer your questions.

1. The code include a `support` variable that equals 1 for distance smaller than 10 meters and 0 otherwise, which is used in the computation of `K`. For points with distance larger than 10 meters, `K` is zeroed by the `support`, which is equivalent for `C` being infinity.
2. No, I did not. For kitti_s I used 8192 points, as done in previous work.

Let me know if you have any further qustions!
